version: '3.1'


# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ~/.docker/volumes/teamcity/data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    user: root
    ports:
      - "8111:8111"
    volumes:
      - ~/.docker/volumes/teamcity/data/teamcity-server-data:/data/teamcity_server/datadir
      - ~/.docker/volumes/teamcity/data/teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - db

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    user: root
    volumes:
      - ./conf/agents/agent-1:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=http://teamcity:8111
  teamcity-agent-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    user: root
    volumes:
      - ./conf/agents/agent-2:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=http://teamcity:8111