version: '3.6'
services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '2222:2222'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ~/.docker/volumes/nginx/data:/usr/share/nginx/html
      - ~/.docker/volumes/nginx/logs:/var/log/nginx
