version: "2.2"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ~/.docker/volumes/mysql/data:/var/lib/mysql
      - ~/.docker/volumes/mysql/logs:/var/log/mysql
